---
title: "Щастя інтровертів"
author: "Тетяна Рибій"
format: 
  html:
    theme: cosmo
---

## ВСТУП

Інтроверсія та екстраверсія в сучасній психологічній науці є одними із провідних особистісних характеристик, які зумовлюють схильність людини до переживання того чи іншого досвіду, та впливають на різноманітність прояву тривалих тенденцій, які зберігаються у часі.

**Актуальність**: Щастя є одним із найголовніших компонентів задоволеності життям та чинників загального благополуччя. Аналіз сучасної літератури, присвяченої феномену суб’єктивного благополуччя, свідчить про численні емпіричні докази існування сильного позитивного кореляційного зв’язку між щастям та екстраверсією. Складається враження, що щастя більш притаманне екстравертам, ніж інтровертам, але чи дійсно це так? Наше припущення полягає у тому, що причиною таких результатів є систематична помилка вимірювання. Саме неточність інструментарію діагностики рівня суб’єктивного благополуччя призводить до таких результатів – питання сформовані таким чином, що не враховують специфічний досвід інтроверта, а націлені на вияв щастя, який притаманний екстраверту. За умови включення у опитувальник питань, які враховували б досвід переживання щастя інтровертів, вказаний зв'язок між рівнем щастя і екстраверсією має зникнути або суттєво зменшитися. 

**Об'єкт**: Щастя.

**Предмет**: Щастя інтровертів.

**Мета**: Виявити той аспект щастя, який не пов'язаний із екстраверсією, та відноситься до досвіду інтровертів.
Гіпотеза: У дослідженнях щастя не враховується досвід інтровертів – опитувальники не містять питань, направлених на вияв специфічного щастя інтроверта, у результаті чого ті набирають менше балів за рівнем щастя.

**Завдання дослідження**: 

1.	Провести теоретичний аналіз особливостей інтроверсії та екстраверсії.

2.	Проаналізувати дані зв’язку рівня щастя із екстраверсією.

3.	Дати характеристику специфічності переживання щастя інтровертами. 

4.	Створити шкалу щастя інтровертів.

5.	Дослідити факторну структуру і надійність шкали щастя інтровертів.

6.	Дослідити зв’язки шкали щастя інтровертів з Оксфордським запитальником щастя, прямими оцінками щастя, екстраверсією і відкритістю новому досвіду. 
**Методи дослідження**: аналіз наукової літератури; глибинне інтерв’ю; емпіричне дослідження з кореляційним дизайном, кореляційний, регресійний і факторний аналіз.

```{r}
library(readxl)
library(psych)
library(sjmisc)

x <- read_excel(
  path = "Щастя (Відповіді).xlsx", skip = 1
)

labs <- read_excel(
  path = "Щастя (Відповіді).xlsx", n_max = 1,
  col_names = names(x)
)

x[] <- mapply(
  FUN = \ (var, lab) { attr(var, "label") <- lab; return(var) },
  x, labs, SIMPLIFY = FALSE
)


## Розподіл відповідей на питання тестів
frq(
  x, E01 : E12, O01 : O12, 
  OHQ01 : OHQ28, T01 : T20, 
  happy, age, gender
)
```

